import React from 'react'
import { Link } from 'react-router-dom'
import { ProductFeature, CallToAction, PageBanner } from '../components/BrandContent'
import useDocumentTitle from '../utils/useDocumentTitle'
export default function MyCanJourney(){
  useDocumentTitle('MyCanJourney — in development')
  const features=[['Profile-led insights','Bring your education, experience, language results, and goals together to understand where you stand.'],['Pathway clarity','Explore possible immigration pathways in relation to your profile and current rules.'],['Score explanations','Understand the factors behind your score and the areas you may be able to improve.'],['Timely reminders','Keep important dates, upcoming tasks, and profile updates in view.'],['Practical next steps','Turn complex information into a clearer set of actions to consider.'],['A journey that evolves','Revisit your options as your circumstances and immigration rules change.']]
  return <div className="ev-page"><PageBanner image="/images/canadian-journey.webp" alt="Illustration of a couple planning their Canadian journey, with a tablet, checklist and Toronto skyline"/><div className="ev-wrap ev-page-intro"><span className="ev-eyebrow">BUILT BY EIGHTVO SOLUTIONS</span><h1>A big life decision.<br/><em>A little more clarity.</em></h1><p>Immigration information can feel overwhelming. We’re creating a more personal, organized way to understand it.</p></div><ProductFeature/><section className="ev-section ev-wrap"><span className="ev-eyebrow">WHAT WE’RE WORKING TOWARD</span><h2>Your journey, connected.</h2><p>These are planned capabilities. MyCanJourney is in development and is not yet available to use.</p><div className="ev-cards">{features.map(([title,copy])=><article className="ev-card" key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="ev-note">MyCanJourney is an independent product in development, not a government service. It is intended to support understanding and planning; it does not guarantee eligibility, invitations, or application outcomes.</p><Link className="ev-text-link" to="/contact">Ask us about MyCanJourney →</Link></section><CallToAction/></div>
}
